


DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(255) = 'Name e054dbf73c584a90b80a3d64def5cdd7'
DECLARE @IsActive BIT = 1
 

DELETE FROM [Analyzer]
FROM 
	[dbo].[Analyzer] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsActive IS NOT NULL THEN (CASE WHEN [IsActive] = @IsActive THEN 1 ELSE 0 END) ELSE 1 END) = 1 
