


DECLARE @ID BIGINT = NULL
DECLARE @Title NVARCHAR(255) = 'Title 389cea31a66144fb8554f89330d638db'
DECLARE @Content NVARCHAR(4000) = 'Content 389cea31a66144fb8554f89330d638db'
DECLARE @Timestamp DATETIME = '6/30/2026 12:36:04 PM'
DECLARE @NewsSourceID BIGINT = 4
DECLARE @Url NVARCHAR(512) = 'Url 389cea31a66144fb8554f89330d638db'
DECLARE @NewsTime DATETIME = '6/30/2026 12:36:04 PM'
 


IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[Article]
				WHERE 
	(CASE WHEN @Title IS NOT NULL THEN (CASE WHEN [Title] = @Title THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Content IS NOT NULL THEN (CASE WHEN [Content] = @Content THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Timestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @Timestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsSourceID IS NOT NULL THEN (CASE WHEN [NewsSourceID] = @NewsSourceID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsTime IS NOT NULL THEN (CASE WHEN [NewsTime] = @NewsTime THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	INSERT INTO [dbo].[Article]
		(
	 [Title],
	 [Content],
	 [Timestamp],
	 [NewsSourceID],
	 [Url],
	 [NewsTime]
		)
	SELECT 		
			 @Title,
	 @Content,
	 @Timestamp,
	 @NewsSourceID,
	 @Url,
	 @NewsTime
END

SELECT TOP 1 
	@ID = [ID]
FROM 
	[dbo].[Article] e
WHERE
	(CASE WHEN @Title IS NOT NULL THEN (CASE WHEN [Title] = @Title THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Content IS NOT NULL THEN (CASE WHEN [Content] = @Content THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Timestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @Timestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsSourceID IS NOT NULL THEN (CASE WHEN [NewsSourceID] = @NewsSourceID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsTime IS NOT NULL THEN (CASE WHEN [NewsTime] = @NewsTime THEN 1 ELSE 0 END) ELSE 1 END) = 1 

SELECT 
	@ID
