


-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @Title NVARCHAR(255) = 'Title 389cea31a66144fb8554f89330d638db'
DECLARE @Content NVARCHAR(4000) = 'Content 389cea31a66144fb8554f89330d638db'
DECLARE @Timestamp DATETIME = '6/30/2026 12:36:04 PM'
DECLARE @NewsSourceID BIGINT = 4
DECLARE @Url NVARCHAR(512) = 'Url 389cea31a66144fb8554f89330d638db'
DECLARE @NewsTime DATETIME = '6/30/2026 12:36:04 PM'
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updTitle NVARCHAR(255) = 'Title 5767b41dc8364c2b88fdae9d653c9ae2'
DECLARE @updContent NVARCHAR(4000) = 'Content 5767b41dc8364c2b88fdae9d653c9ae2'
DECLARE @updTimestamp DATETIME = '6/30/2026 12:36:04 PM'
DECLARE @updNewsSourceID BIGINT = 5
DECLARE @updUrl NVARCHAR(512) = 'Url 5767b41dc8364c2b88fdae9d653c9ae2'
DECLARE @updNewsTime DATETIME = '9/28/2026 8:09:04 AM'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Article]
				WHERE 
	(CASE WHEN @updTitle IS NOT NULL THEN (CASE WHEN [Title] = @updTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updContent IS NOT NULL THEN (CASE WHEN [Content] = @updContent THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTimestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @updTimestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNewsSourceID IS NOT NULL THEN (CASE WHEN [NewsSourceID] = @updNewsSourceID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUrl IS NOT NULL THEN (CASE WHEN [Url] = @updUrl THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNewsTime IS NOT NULL THEN (CASE WHEN [NewsTime] = @updNewsTime THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Article]
	WHERE 
	(CASE WHEN @Title IS NOT NULL THEN (CASE WHEN [Title] = @Title THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Content IS NOT NULL THEN (CASE WHEN [Content] = @Content THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Timestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @Timestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsSourceID IS NOT NULL THEN (CASE WHEN [NewsSourceID] = @NewsSourceID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NewsTime IS NOT NULL THEN (CASE WHEN [NewsTime] = @NewsTime THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Article]
	WHERE 
	(CASE WHEN @updTitle IS NOT NULL THEN (CASE WHEN [Title] = @updTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updContent IS NOT NULL THEN (CASE WHEN [Content] = @updContent THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTimestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @updTimestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNewsSourceID IS NOT NULL THEN (CASE WHEN [NewsSourceID] = @updNewsSourceID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUrl IS NOT NULL THEN (CASE WHEN [Url] = @updUrl THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNewsTime IS NOT NULL THEN (CASE WHEN [NewsTime] = @updNewsTime THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Article was not updated', 1
END