


DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 47aad278965f4dbaa558358e8acc9381'
 

DELETE FROM [SentimentType]
FROM 
	[dbo].[SentimentType] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
