


DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name c805cbccbe5a44f6949a29d00d1fdff4'
 


IF(EXISTS(SELECT 1 FROM 
					[dbo].[SentimentType]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM [dbo].[SentimentType]
WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 

END