


DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(255) = 'Name edd3cbe9382d4149a061cbeb18246bbe'
DECLARE @Url NVARCHAR(255) = 'Url edd3cbe9382d4149a061cbeb18246bbe'
DECLARE @IsActive BIT = 1
 


IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[NewsSource]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsActive IS NOT NULL THEN (CASE WHEN [IsActive] = @IsActive THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	INSERT INTO [dbo].[NewsSource]
		(
	 [Name],
	 [Url],
	 [IsActive]
		)
	SELECT 		
			 @Name,
	 @Url,
	 @IsActive
END

SELECT TOP 1 
	@ID = [ID]
FROM 
	[dbo].[NewsSource] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsActive IS NOT NULL THEN (CASE WHEN [IsActive] = @IsActive THEN 1 ELSE 0 END) ELSE 1 END) = 1 

SELECT 
	@ID
