


DECLARE @ID BIGINT = NULL
DECLARE @Timestamp DATETIME = '12/21/2027 5:58:04 AM'
DECLARE @ArticleID BIGINT = 18
DECLARE @SentimentID BIGINT = 4
DECLARE @AnalyzerID BIGINT = 8
 
DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[ArticleAnalysis]
				WHERE 
	(CASE WHEN @Timestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @Timestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ArticleID IS NOT NULL THEN (CASE WHEN [ArticleID] = @ArticleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SentimentID IS NOT NULL THEN (CASE WHEN [SentimentID] = @SentimentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @AnalyzerID IS NOT NULL THEN (CASE WHEN [AnalyzerID] = @AnalyzerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	SET @Fail = 1
END

DELETE FROM 
	[dbo].[ArticleAnalysis]
	WHERE 
	(CASE WHEN @Timestamp IS NOT NULL THEN (CASE WHEN [Timestamp] = @Timestamp THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ArticleID IS NOT NULL THEN (CASE WHEN [ArticleID] = @ArticleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SentimentID IS NOT NULL THEN (CASE WHEN [SentimentID] = @SentimentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @AnalyzerID IS NOT NULL THEN (CASE WHEN [AnalyzerID] = @AnalyzerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

IF(@Fail = 1) 
BEGIN
	THROW 51001, 'ArticleAnalysis was not inserted', 1
END